// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ZlI9-jkQkpTZvjUpAvnkZc4r2x_cBko',
    appId: '1:254460932244:web:bc78785376c777fa758481',
    messagingSenderId: '254460932244',
    projectId: 'project-3-2c034',
    authDomain: 'project-3-2c034.firebaseapp.com',
    storageBucket: 'project-3-2c034.appspot.com',
    measurementId: 'G-X3HZ0RDYC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqfRbgvG-lVp2kkaZE8HlsefzPC5KvFqs',
    appId: '1:254460932244:android:ab918660015cd147758481',
    messagingSenderId: '254460932244',
    projectId: 'project-3-2c034',
    storageBucket: 'project-3-2c034.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNzYZp769-HQIqSCCSkCJi88k44ifZA7U',
    appId: '1:254460932244:ios:5c65925ffaefb524758481',
    messagingSenderId: '254460932244',
    projectId: 'project-3-2c034',
    storageBucket: 'project-3-2c034.appspot.com',
    iosClientId: '254460932244-pbm2acjcatdoma4d97ph3ifv93vae16j.apps.googleusercontent.com',
    iosBundleId: 'com.example.project3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNzYZp769-HQIqSCCSkCJi88k44ifZA7U',
    appId: '1:254460932244:ios:5c65925ffaefb524758481',
    messagingSenderId: '254460932244',
    projectId: 'project-3-2c034',
    storageBucket: 'project-3-2c034.appspot.com',
    iosClientId: '254460932244-pbm2acjcatdoma4d97ph3ifv93vae16j.apps.googleusercontent.com',
    iosBundleId: 'com.example.project3',
  );
}
